github_url = "https://github.com/weltenwort/py-hpsu-monitor/"

[version]
current = "0.2.2"

# Example of a semver regexp.
# Make sure this matches current_version before
# using tbump
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''

[git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

[[file]]
src = "pyproject.toml"
search = '^version = "{current_version}"$'

[[file]]
src = "py_hpsu_monitor/__init__.py"
search = '^__version__ = "{current_version}"$'
